print("Counting up from 0 to 50:")
for num in range (0,51,1):
    print(num)

print("\ncounting down from 50 to 0:")
for num in range(50,-1,-1):
    print(num)

print("\nCounting up from 30 to 50")
for num in range (30,51,1):
    print(num)

print("\nCounting down from 50 to 10 in decrement of 2:")
for num in range (50, 9,-2):
    print(num)

print("\nCounting up from 100 to 200 in increment of 5:")
for num in range (100, 201, 5):
    print(num)